add code for comapring version and creating issue
Signed-off-by: Rizul Gupta <mail2rizul@gmail.com>

diff --git a/.github/workflows/update-helm-chart.yml b/.github/workflows/update-helm-chart.yml
--- a/.github/workflows/update-helm-chart.yml
+++ b/.github/workflows/update-helm-chart.yml
@@ -1,10 +1,12 @@
 name: Upgrade Helm Chart
 on:
-    schedule:
-        - cron: '0 1 * * 1-5'
+  schedule:
+    - cron: '0 1 * * 1-5'
+
 defaults:
   run:
     shell: bash
+
 jobs:
   upgrade-helm-chart:
     name: Upgrade Helm Chart
@@ -14,32 +16,60 @@ jobs:
         config:
           - name: keptn
             path: chart
-          - name: keptn-lifecycle-operator
-            path: lifecycle-operator/chart
-          - name: keptn-metrics-operator
-            path: metrics-operator/chart
-          - name: keptn-cert-manager
-            path: keptn-cert-manager/chart
 
     steps:
       - name: Check out code
         uses: actions/checkout@v4
+
       - name: Install Helm
         run: |
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
           chmod 700 get_helm.sh
-          ./get_helm.sh      
+          ./get_helm.sh
+
+      - name: Install Helm Chart
+        uses: ./.github/actions/install-helm-chart
+
       - name: Upgrade Helm Chart
         id: check-upgrades
         run: |
+          export HELM_OLDER=$(helm list -A | grep keptn | awk '{print $9}')
+          HELM_UPGRADE_OUTPUT=$(helm upgrade keptn ./chart --install --namespace keptn --create-namespace)
+          export HELM_NEWER=$(helm list -A | grep keptn | awk '{print $9}')
+          if [ $? -ne 0 ]; then
+            echo "Helm upgrade failed. Opening issue..."
+            export UPGRADE_ERROR_MESSAGE=$(echo "$HELM_UPGRADE_OUTPUT" | tail -n 1)
+            echo "::set-output name=upgrade_failed::true"
+            echo "::set-output name=upgrade_error_message::$UPGRADE_ERROR_MESSAGE"
+          fi
 
-      - name: Open Issue for Upgrade Failure
-        if: steps.check-upgrades.outputs.exit-code != 0
-        uses: peter-evans/create-issue-from-file@v2
-        with:
-          title: Upgrade Failed for Helm Chart
-          body: |
-            Upgrade for the Helm chart failed. Please investigate and fix the issue.
-          labels: bug
- 
+      - name: Compare Helm Versions
+        id: compare-versions
+        run: |
+          if [ "$HELM_NEWER" != "$HELM_OLDER" ]; then
+            echo "New version available: $HELM_NEWER"
+            echo "::set-output name=new_version::true"
+          else
+            echo "No new version available"
+            echo "::set-output name=new_version::false"
+          fi
+
+  create-issue:
+    name: Create Issue on Upgrade Failure
+    needs: upgrade-helm-chart
+    runs-on: ubuntu-22.04
+    if: needs.upgrade-helm-chart.outputs.upgrade_failed == 'true'
+    steps:
+      - name: Create Issue
+        run: |
+          echo "Creating issue..."
+          ACCESS_TOKEN="${{ secrets.ACCESS_TOKEN }}"
+          REPO_OWNER="${{ github.repository_owner }}"
+          REPO_NAME="${{ github.event.repository.name }}"
+          ISSUE_TITLE="${{ needs.upgrade-helm-chart.outputs.upgrade_error_message }}"
+          ISSUE_BODY="The Helm upgrade for the keptn chart has failed with the following error message:\n\n\`${{ needs.upgrade-helm-chart.outputs.upgrade_error_message }}\`"
           
+          curl -X POST -H "Authorization: token $ACCESS_TOKEN" \
+               -H "Accept: application/vnd.github.v3+json" \
+               https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues \
+               -d "{\"title\":\"$ISSUE_TITLE\",\"body\":\"$ISSUE_BODY\"}"
